const Constants = {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    FETCH_ITEMS: 'FETCH_ITEMS',
    FETCH_ITEM: 'FETCH_ITEM',
    POST_TRANSACTION: 'POST_TRANSACTION',
    SET_ITEM: 'SET_ITEM'
}

export default Constants;